<?php

/**
 * @var string $yacov_url
 */

?>
<h2 class="wt-page-title">About</h2>

<div class="card">
    <div class="card-body">
        <p class="text-justify">
            Anyone who’s ever been to a genealogy convention or lecture will tell you that the average age
            of the audience is pushing 70. Why we start getting interested in our roots late in life is a
            separate question, but for me, it started when my kids came home from school one day with an
            assignment to tell their respective classes about their ancestry. I was embarrassed that all I
            had to give them were a very few basic facts about my parents. But it was the birth of my first
            grandson, <a href="http://individual.php?pid=I78&amp;ged=levy.ged">Jonah</a>, which finally
            prompted me to try and put together a family history site for him and my other grandchildren.
        </p>

        <p class="text-justify">
            Unfortunately, by then, not only both my parents were gone but so was almost everyone else who
            could have shed some light on my family’s history. Luckily, my parents left behind manuscripts
            and documents which contained a great deal of information that was helpful in rebuilding quite
            a bit of their history and of some of their ancestors. Thus began a long journey that took me,
            among other places, to Vilnius, Lithuania and to a remote village in rural Ukraine.
        </p>

        <p class="text-justify">
            As my research progressed, I discovered in various parts of the world (partially through DNA
            testing) relatives I didn’t know existed and also reconnected with others with whom I haven’t
            been in touch for decades. They too have great stories to tell and much of it is on this site.
        </p>

        <p class="text-justify">
            While building the site I realized that parts of it have historical value of their own, which I
            hope will be helpful to other people in their research. (You might want to check out my
            father’s <a href="<?= e($yacov_url) ?>">diary from his service in
            the Ottoman army during WWI</a>.)
        </p>

        <p class="text-center">
            * * *
        </p>

        <p class="text-justify">
            A final note: A great deal of the material on this site is based on my parents’ documents, my
            father’s writings and other genealogical research. When it comes to my own parents, however, in
            trying to make their life stories complete, I had to use a number of sources that were not
            always fully verifiable. I also made some logical assumptions based on my research, on my
            father’s writings and, on a few occasions, on family lore.
        </p>
    </div>
</div>
